server:
  port:8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    baseline-on-migrate: true
